STATE_ABBR = dict(
  AK = 'Alaska',
  AL = 'Alabama',
  AR = 'Arkansas',
  AZ = 'Arizona',
  CA = 'California',
  CO = 'Colorado',
  CT = 'Connecticut',
  DC = 'District Of Columbia',
  DE = 'Delaware',
  FL = 'Florida',
  GA = 'Georgia',
  HI = 'Hawaii',
  IA = 'Iowa',
  ID = 'Idaho',
  IL = 'Illinois',
  IN = 'Indiana',
  KS = 'Kansas',
  KY = 'Kentucky',
  LA = 'Louisiana',
  MA = 'Massachusetts',
  MD = 'Maryland',
  ME = 'Maine',
  MI = 'Michigan',
  MN = 'Minnesota',
  MO = 'Missouri',
  MS = 'Mississippi',
  MT = 'Montana',
  NC = 'North Carolina',
  ND = 'North Dakota',
  NE = 'Nebraska',
  NH = 'New Hampshire',
  NJ = 'New Jersey',
  NM = 'New Mexico',
  NV = 'Nevada',
  NY = 'New York',
  OH = 'Ohio',
  OK = 'Oklahoma',
  OR = 'Oregon',
  PA = 'Pennsylvania',
  RI = 'Rhode Island',
  SC = 'South Carolina',
  SD = 'South Dakota',
  TN = 'Tennessee',
  TX = 'Texas',
  UT = 'Utah',
  VA = 'Virginia',
  VT = 'Vermont',
  WA = 'Washington',
  WI = 'Wisconsin',
  WV = 'West Virginia',
  WY = 'Wyoming'
)

STATE_MISPELLINGS = dict(
  nebraksa    = "NE",
  minneosta   = "MN",
  missourri   = "MI",
  ilinois     = "IL",
  pennsyvania = "PA"
)

COUNTRIES = { 
  "afghanistan"                      : "Afghanistan",
  "albania"                          : "Albania",
  "algeria"                          : "Algeria",
  "angola"                           : "Angola",
  "antarctica"                       : "Antarctica",
  "argentina"                        : "Argentina",
  "australia"                        : "Australia",
  "austria"                          : "Austria",
  "azerbaijan"                       : "Azerbaijan",
  "bahrain"                          : "Bahrain",
  "bangladesh"                       : "Bangladesh",
  "barbados"                         : "Barbados",
  "belarus"                          : "Belarus",
  "belgium"                          : "Belgium",
  "benin"                            : "Benin",
  "bhutan"                           : "Bhutan",
  "bolivia"                          : "Bolivia",
  "bosnia_and_herzegovina"           : "Bosnia and Herzegovina",
  "brazil"                           : "Brazil",
  "bulgaria"                         : "Bulgaria",
  "burkina_faso"                     : "Burkina Faso",
  "cambodia"                         : "Cambodia",
  "cameroon"                         : "Cameroon",
  "canada"                           : "Canada",
  "central_african_republic"         : "Central African Republic",
  "chile"                            : "Chile",
  "china"                            : "China",
  "colombia"                         : "Colombia",
  "cook_islands"                     : "Cook Islands",
  "costa_rica"                       : "Costa Rica",
  "cote_d'ivoire"                    : "Cote d'Ivoire",
  "cote_divoire"                     : "Cote d'Ivoire",
  "croatia"                          : "Croatia",
  "cuba"                             : "Cuba",
  "cyprus"                           : "Cyprus",
  "czech_republic"                   : "Czech Republic",
  "czechoslovakia"                   : "Czechoslovakia",
  "democratic_republic_of_the_congo" : "Democratic Republic of the Congo",
  "denmark"                          : "Denmark",
  "djibouti"                         : "Djibouti",
  "dominican_republic"               : "Dominican Republic",
  "ecuador"                          : "Ecuador",
  "egypt"                            : "Egypt",
  "el_salvador"                      : "El Salvador",
  "estonia"                          : "Estonia",
  "ethiopia"                         : "Ethiopia",
  "europe"                           : "Europe",
  "fiji"                             : "Fiji",
  "finland"                          : "Finland",
  "france"                           : "France",
  "french_guiana"                    : "French Guiana",
  "french_polynesia"                 : "French Polynesia",
  "gaza_strip"                       : "Gaza Strip",
  "georgia"                          : "Georgia",
  "germany"                          : "Germany",
  "ghana"                            : "Ghana",
  "gibraltar"                        : "Gibraltar",
  "greece"                           : "Greece",
  "greenland"                        : "Greenland",
  "guadeloupe"                       : "Guadeloupe",
  "guam"                             : "Guam",
  "guatemala"                        : "Guatemala",
  "haiti"                            : "Haiti",
  "honduras"                         : "Honduras",
  "hong_kong"                        : "Hong Kong",
  "hungary"                          : "Hungary",
  "iceland"                          : "Iceland",
  "india"                            : "India",
  "indonesia"                        : "Indonesia",
  "iran"                             : "Iran",
  "iraq"                             : "Iraq",
  "ireland"                          : "Ireland",
  "israel"                           : "Israel",
  "italy"                            : "Italy",
  "jamaica"                          : "Jamaica",
  "japan"                            : "Japan",
  "jordan"                           : "Jordan",
  "kazakhstan"                       : "Kazakhstan",
  "kenya"                            : "Kenya",
  "korea"                            : "Korea",
  "kosovo"                           : "Kosovo",
  "kuwait"                           : "Kuwait",
  "kyrgyzstan"                       : "Kyrgyzstan",
  "lab"                              : "UKNOWN",
  "laos"                             : "Laos",
  "latvia"                           : "Latvia",
  "lebanon"                          : "Lebanon",
  "libya"                            : "Libya",
  "lithuania"                        : "Lithuania",
  "luxembourg"                       : "Luxembourg",
  "macau"                            : "Macau",
  "madagascar"                       : "Madagascar",
  "malaysia"                         : "Malaysia",
  "mali"                             : "Mali",
  "mauritius"                        : "Mauritius",
  "mexico"                           : "Mexico",
  "middle_east"                      : "Middle East",
  "moldova"                          : "Moldova",
  "mongolia"                         : "Mongolia",
  "montenegro"                       : "Montenegro",
  "montserrat"                       : "Montserrat",
  "morocco"                          : "Morocco",
  "mozambique"                       : "Mozambique",
  "myanmar"                          : "Myanmar",
  "nepal"                            : "Nepal",
  "netherlands"                      : "Netherlands",
  "new_caledonia"                    : "New Caledonia",
  "new_zealand"                      : "New Zealand",
  "nicaragua"                        : "Nicaragua",
  "niger"                            : "Niger",
  "nigeria"                          : "Nigeria",
  "north_korea"                      : "North Korea",
  "northern_mariana_islands"         : "Northern Mariana Islands",
  "norway"                           : "Norway",
  "oman"                             : "Oman",
  "pakistan"                         : "Pakistan",
  "panama"                           : "Panama",
  "papua_new_guinea"                 : "Papua New Guinea",
  "paraguay"                         : "Paraguay",
  "peru"                             : "Peru",
  "philippines"                      : "Philippines",
  "poland"                           : "Poland",
  "portugal"                         : "Portugal",
  "puerto_rico"                      : "Puerto Rico",
  "qatar"                            : "Qatar",
  "reunion"                          : "Reunion",
  "romania"                          : "Romania",
  "russia"                           : "Russia",
  "saudi_arabia"                     : "Saudi Arabia",
  "senegal"                          : "Senegal",
  "serbia"                           : "Serbia",
  "singapore"                        : "Singapore",
  "slovakia"                         : "Slovakia",
  "slovenia"                         : "Slovenia",
  "solomon_islands"                  : "Solomon Islands",
  "south_africa"                     : "South Africa",
  "south_korea"                      : "South Korea",
  "spain"                            : "Spain",
  "sri_lanka"                        : "Sri Lanka",
  "state_of_palestine"               : "State of Palestine",
  "sudan"                            : "Sudan",
  "suriname"                         : "Suriname",
  "sweden"                           : "Sweden",
  "switzerland"                      : "Switzerland",
  "taiwan"                           : "Taiwan",
  "tanzania"                         : "Tanzania",
  "thailand"                         : "Thailand",
  "togo"                             : "Togo",
  "tonga"                            : "Tonga",
  "trinidad_and_tobago"              : "Trinidad and Tobago",
  "tunisia"                          : "Tunisia",
  "turkey"                           : "Turkey",
  "turkmenistan"                     : "Turkmenistan",
  "usa"                              : "USA",
  "ussr"                             : "USSR",
  "uganda"                           : "Uganda",
  "ukraine"                          : "Ukraine",
  "united_arab_emirates"             : "United Arab Emirates",
  "united_kingdom"                   : "United Kingdom",
  "uruguay"                          : "Uruguay",
  "uzbekistan"                       : "Uzbekistan",
  "venezuela"                        : "Venezuela",
  "viet_nam"                         : "Viet Nam",
  "west_bank"                        : "West Bank",
  "zambia"                           : "Zambia",
  "zimbabwe"                         : "Zimbabwe"
}
