PREFIX onto: <http://www.ontotext.com/>
PREFIX f: <https://flu-crew.org/term/>
PREFIX fid: <https://flu-crew.org/id/>
PREFIX world: <https://flu-crew.org/geo/country/>
PREFIX usa: <https://flu-crew.org/geo/country/usa/>

# count the unique strains in the database that have genbank data, aggregated by host

SELECT ?host (COUNT(DISTINCT ?strain) as ?nstrains)
FROM onto:disable-sameAs
WHERE {
    ?sid f:strain_name ?strain .
    ?sid f:has_segment ?gid .
    ?sid f:host ?host .
    ?gid f:dnaseq ?seq .
}
GROUP BY ?host
ORDER BY DESC(?nstrains)
