PREFIX f: <https://flu-crew.org/term/>
PREFIX onto: <http://www.ontotext.com/>

SELECT DISTINCT ?gb
FROM onto:disable-sameAs
WHERE {
    {
        ?sid f:host "swine" .
        ?sid f:has_segment/f:genbank_id ?gb .
    } UNION {
        ?sid f:tag/f:name ?tag .
        ?sid f:has_segment/f:genbank_id ?gb .
    }
}
