PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX f: <https://flu-crew.org/term/>

# build.py does not download all the genbank files for all the strains (that
# would be a lot of work) so it is necessary to retrive the genbank ids of
# interest and then pipe them into `build.py add_gbids`. This query retrieves
# the genbank ids for all strains tagged as swine references.
SELECT DISTINCT ?gb
WHERE {
    ?sid f:has_genbank ?gb
    ?sid f:tag/f:name "swine-reference" .
}
