PREFIX f: <https://flu-crew.org/term/>

SELECT DISTINCT ?gb
WHERE {
    # ?sid f:has_segment/f:genbank_id ?gb .
    # ?sid f:host "swine" .

    ?sid f:host ?host .
    ?sid f:has_segment/f:genbank_id ?gb .

    OPTIONAL { ?sid f:epi_id ?epi }

    FILTER (?host = "swine" || ! BOUND(?epi)) .
}
